mainapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('list/', views.notice_list, name='notice_list'),                   
    path('detail/<int:notice_id>', views.notice_detail, name='notice_detail'),                        
    path('register/', views.notice_register, name='notice_register'),                        
    path('update/<int:notice_id>', views.notice_update, name='notice_update'), 
    path('delete/<int:notice_id>', views.notice_delete, name='notice_delete'),
    path('weather/', views.weather, name='weather'),
    path('transport/', views.transport, name='transport'),             
 
]

sookmyungproject/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.views.home, name='home'),
    path('accounts/', include('accountsapp.urls')),
    path('library/', include('libraryapp.urls')),
    path('sookplace/', include('sookplaceapp.urls')),
    path('main/', include('mainapp.urls')),
    #path('transport/', include('transportapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sookplaceapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'sookplaceapp'

urlpatterns = [
    path('list/', views.sookplace_list, name='sookplace_list'),                   
    path('detail/<int:sookplace_id>', views.sookplace_detail, name='sookplace_detail'),                        
    path('register/', views.sookplace_register, name='sookplace_register'),                        
    path('update/<int:sookplace_id>', views.sookplace_update, name='sookplace_update'), 
    path('delete/<int:sookplace_id>', views.sookplace_delete, name='sookplace_delete'),             
]

sookplaceapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Sookplace(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    address = models.TextField()
    detail_addr = models.TextField()
    describe = models.TextField()
    photo = models.ImageField(null=True,blank=True, upload_to='sookplace/')

    def __str__(self):
        return self.title

sookplaceapp/forms.py
from django import forms
from .models import Sookplace

class SookplaceForm(forms.ModelForm):
    class Meta:
        model = Sookplace
        fields = ['title', 'address', 'detail_addr', 'describe', 'photo']
    

sookplaceapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Sookplace
from .forms import SookplaceForm
from django.contrib.auth.models import User



# Create your views here.
#게시물 리스트
def sookplace_list(request):
    sookplaces = Sookplace.objects               
    return render(request, 'sookplaceapp/sookplace_list.html', {'sookplaces' : sookplaces})


#게시물 상세페이지 (R)
def sookplace_detail(request, sookplace_id):
    sookplace = get_object_or_404(Sookplace, pk=sookplace_id)
    return render(request, 'sookplaceapp/sookplace_detail.html', {'sookplace':sookplace})

#게시물 등록 (C)
@login_required
def sookplace_register(request):
    if request.method == 'POST':
        form = SookplaceForm(request.POST, request.FILES)
        if form.is_valid():
            sookplace = form.save(commit=False)
            sookplace.user = request.user  ##username 자동 설정
            sookplace.save()
            return redirect('sookplaceapp:sookplace_list')
    else : 
        form=SookplaceForm()
        return render(request, 'sookplaceapp/sookplace_register.html', {'form':form})

#게시물 수정(U)
@login_required
def sookplace_update(request, sookplace_id):
    sookplace = get_object_or_404(Sookplace, pk=sookplace_id)
    if request.method=='POST':
        form = SookplaceForm(request.POST, instance=sookplace)
        if form.is_valid():
            sookplace = form.save(commit=False)
            sookplace.user = request.user  ##username 자동 설정
            sookplace.save()
            return redirect('sookplaceapp:sookplace_detail', sookplace_id=sookplace.pk)    
    else:
        if sookplace.user == User.objects.get(username=request.user.get_username()) :  ##자신의 글일때만 수정 가능
            form = SookplaceForm(instance=sookplace)
            return render(request, 'sookplaceapp/sookplace_update.html', {'form':form})

        else :
            return redirect('sookplaceapp:sookplace_detail', sookplace_id=sookplace.pk)    ##자신의 글 아니면 해당글 detail로 redirect


#게시물 삭제(D)
@login_required
def sookplace_delete(request, sookplace_id):
    sookplace = get_object_or_404(Sookplace, pk=sookplace_id)
    if sookplace.user == User.objects.get(username=request.user.get_username()) : ##자신의 글일때만 삭제 가능
        sookplace.delete()
        return redirect('sookplaceapp:sookplace_list')
    else:
        return redirect('sookplaceapp:sookplace_detail', sookplace_id=sookplace.pk)   ##자신의 글 아니면 해당글 detail로 redirect

sookplaceapp/templates/sookplaceapp/sookplace_detail.html
<!---->
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style>
                #map{
                margin: auto;
                width: 50%;
                }
                a{text-decoration:none;color:black; !important}

            </style>

        </head>

        <body style="text-align:center;">
            <div style="width:100%;display:inline-block;">
                <h2 style="margin-top:12%">맛집 리스트</h2>
                    <div style="display:inline-block;width:90%; height:2px; background-color:#171717; margin:40px 0 60px 0;"></div><br>
                    <span style="font-size: 20pt;">{{ sookplace.title }}</span><br><br>

                <div style="display:inline-block;width:80%" id="lib_content">
                    <br>
                    <img src ="{{ sookplace.photo.url }}" width=200> <br>
                    <br>
                    {{ sookplace.date }} <br>
                    {{ sookplace.address }} <br>
                    {{ sookplace.detail_addr }} <br>
                    {{ sookplace.describe }} <br>
                </div><br>

                <!--다음지도api - 배포시 다음에서 플랫폼 도메인 주소 바꾸기!-->
                <!--https://developers.kakao.com/apps/367921/settings/general-->

                <div id="map" style="width:200px;height:200px; vertical-align:middle;"></div>

                <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=88fef5eac83ce4f2e8d43c348fcb0e0b&libraries=services"></script>
                <script>
                    var mapContainer = document.getElementById('map'), // 지도를 표시할 div
                        mapOption = {
                            center: new kakao.maps.LatLng(33.450701, 126.570667), // 지도의 중심좌표
                            level: 3 // 지도의 확대 레벨
                        };

                    // 지도를 생성합니다
                    var map = new kakao.maps.Map(mapContainer, mapOption);

                    // 주소-좌표 변환 객체를 생성합니다
                    var geocoder = new kakao.maps.services.Geocoder();

                    // 주소로 좌표를 검색합니다
                    geocoder.addressSearch('{{ sookplace.address }}', function(result, status) {

                        // 정상적으로 검색이 완료됐으면
                        if (status === kakao.maps.services.Status.OK) {

                            var coords = new kakao.maps.LatLng(result[0].y, result[0].x);

                            // 결과값으로 받은 위치를 마커로 표시합니다
                            var marker = new kakao.maps.Marker({
                                map: map,
                                position: coords
                            });

                            // 인포윈도우로 장소에 대한 설명을 표시합니다
                            var infowindow = new kakao.maps.InfoWindow({
                                content: '<div style="width:150px;text-align:center;padding:6px 0;">{{ sookplace.title }}</div>'
                            });
                            infowindow.open(map, marker);

                            // 지도의 중심을 결과값으로 받은 위치로 이동시킵니다
                            map.setCenter(coords);
                        }
                    });
                </script>
            </div>



            <br>
            <div style="float:right; margin-right:10%;">
                {% if request.user == sookplace.user %}
                <a style="margin-right:10px;box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;display:inline-block;border-radius:5px;" href="{% url 'sookplaceapp:sookplace_update' sookplace.id %}">수정하기</a>
                <a style="box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;display:inline-block;border-radius:5px;" href="{% url 'sookplaceapp:sookplace_delete' sookplace.id %}">삭제하기</a>
                <a style="box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;display:inline-block;border-radius:5px;" href="{% url 'sookplaceapp:sookplace_list' %}">글 목록</a>
                {% endif %}
            </div>


        </body>
    </html>


{% endblock %}

sookplaceapp/templates/sookplaceapp/sookplace_list.html
    <!DOCTYPE html>
    <html>
        <head>
            <style>
                a{text-decoration:none;color:black; !important}

            </style>
        </head>
        {% extends 'base.html' %}

        {% block content %}
        <body style="text-align: center;">
            <h2 style="margin-top:12%">숙플레이스</h2>

            <div id="lib_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">
            <!--글목록-->
            <div class = "container">
            {% for sookplace in sookplaces.all %}
            <br>
            <div id="Sookplace_link" style="display:inline-block;width:95%;height:50px;border-bottom: 1px solid #848484;">
                <a href="{% url 'sookplaceapp:sookplace_detail' sookplace.id %}" style="margin-left:-65%;font-weight: bold; font-size: 14pt; color: #1D375F;">{{ sookplace.title }}</a>
                <span style="float:right;margin-right:30px;color:848484">{{ sookplace.user }} {{ sookplace.date }}</span>
            </div><br>
            {% endfor %}
            </div><br>

            <a style="float:right; margin-right:10%;box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;line-height:30px;display:inline-block;border-radius:5px; " href="{% url 'sookplaceapp:sookplace_register' %}" style="color: #1D375F; font-weight: bold;">글쓰기</a>

            <br>

        </body>
        {% endblock %}
    </html>

sookplaceapp/templates/sookplaceapp/sookplace_register.html
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style>
            #id_title{width:700px;}
            textarea{resize:none; width:700px;height:250px;}
                a{text-decoration:none;color:white; !important}


            </style>

        </head>

        <body style="text-align:center;">
            <h2 style="margin-top:12%">글 작성</h2>
            <div id="lib_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">
            <form style="margin:50px 0 10px 0;" method="POST" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <span style="margin-right:10px;"></span>

                <span style="margin-right:10px;">제   목</span> {{ form.title }} <br><br>   <!--title 입력 폼-->
                <span style="display:inline-block;vertical-align:top;margin-right:10px;margin-left:-1%;">내   용</span> {{ form.describe }}<br>
                <span style="margin-right:10px;">사   진</span> {{ form.photo }}<br>
                <span style="margin-right:10px;">주   소</span> {{ form.homepage }}

                    <!--다음 api-->


                    <input type="text"  id="sample6_postcode" placeholder="우편번호">
                    <input type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기"><br>
                    <input type="text" name="address" id="sample6_address" placeholder="주소">  <!--address-->
                    <input type="text" name="detail_addr" id="sample6_detailAddress" placeholder="상세주소"> <!--detailaddr-->
                    <input type="text" id="sample6_extraAddress" placeholder="참고항목">

                    <script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
                    <script>
                        function sample6_execDaumPostcode() {
                            new daum.Postcode({
                                oncomplete: function(data) {
                                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                                var addr = ''; // 주소 변수
                                var extraAddr = ''; // 참고항목 변수

                                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                                    addr = data.roadAddress;
                                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                                    addr = data.jibunAddress;
                                }

                                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                                if(data.userSelectedType === 'R'){
                                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                                    // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                                        extraAddr += data.bname;
                                    }
                                    // 건물명이 있고, 공동주택일 경우 추가한다.
                                    if(data.buildingName !== '' && data.apartment === 'Y'){
                                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                                    }
                                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                                    if(extraAddr !== ''){
                                        extraAddr = ' (' + extraAddr + ')';
                                    }
                                    // 조합된 참고항목을 해당 필드에 넣는다.
                                    document.getElementById("sample6_extraAddress").value = extraAddr;

                                } else {
                                    document.getElementById("sample6_extraAddress").value = '';
                                }

                                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                                document.getElementById('sample6_postcode').value = data.zonecode;
                                document.getElementById("sample6_address").value = addr;
                                // 커서를 상세주소 필드로 이동한다.
                                document.getElementById("sample6_detailAddress").focus();
                                }
                            }).open();
                        }
                </script>

                </div>

                <br>
                <input type="submit" value="등록">
            </form>
            </div>

        </body>
    </html>


{% endblock %}

sookplaceapp/templates/sookplaceapp/sookplace_update.html
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style type="text/css">
                a{text-decoration:none;color:black; !important}
                #id_title{width:700px;}
                textarea{resize:none; width:700px;height:250px;}
                #map{margin: auto;width: 50%;}
            </style>
        </head>

        <body style="text-align:center;">
            <h2 style="margin-top:12%">글 수정</h2>
            <div id="lib_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">

                <form  style="margin:50px 0 0 0" method="POST" enctype="multipart/form-data" novalidate>
                    {% csrf_token %}
                    <span style="margin-right:10px;"></span>

                    <span style="margin-right:10px;">제   목</span> {{ form.title }} <br><br>   <!--title 입력 폼-->
                    <span style="display:inline-block;vertical-align:top;margin-right:10px;margin-left:-1%;">내   용</span> {{ form.describe }}<br>
                    <span style="margin-right:10px;">사   진</span> {{ form.photo }}<br>
                    <span style="margin-right:10px;">주   소</span> {{ form.homepage }}

                    <input type="text"  id="sample6_postcode" placeholder="우편번호">
                    <input type="button" onclick="sample6_execDaumPostcode()" value="우편번호 찾기"><br>
                    <input type="text" name="address" id="sample6_address" placeholder="주소">  <!--address-->
                    <input type="text" name="detail_addr" id="sample6_detailAddress" placeholder="상세주소"> <!--detailaddr-->
                    <input type="text" id="sample6_extraAddress" placeholder="참고항목"><br>

                    <script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
                    <script>
                        function sample6_execDaumPostcode() {
                            new daum.Postcode({
                                oncomplete: function(data) {
                                    var addr = ''; // 주소 변수
                                    var extraAddr = ''; // 참고항목 변수
                                    //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                                    if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                                        addr = data.roadAddress;
                                    } else { // 사용자가 지번 주소를 선택했을 경우(J)
                                        addr = data.jibunAddress;
                                    }
                                    // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.
                                    if(data.userSelectedType === 'R'){
                                        // 법정동명이 있을 경우 추가한다. (법정리는 제외)
                                        // 법정동의 경우 마지막 문자가 "동/로/가"로 끝난다.
                                        if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){
                                            extraAddr += data.bname;
                                        }
                                        // 건물명이 있고, 공동주택일 경우 추가한다.
                                        if(data.buildingName !== '' && data.apartment === 'Y'){
                                            extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                                        }
                                        // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.
                                        if(extraAddr !== ''){
                                            extraAddr = ' (' + extraAddr + ')';
                                        }
                                        // 조합된 참고항목을 해당 필드에 넣는다.
                                        document.getElementById("sample6_extraAddress").value = extraAddr;
                                    } else {
                                        document.getElementById("sample6_extraAddress").value = '';
                                    }

                                    // 우편번호와 주소 정보를 해당 필드에 넣는다.
                                    document.getElementById('sample6_postcode').value = data.zonecode;
                                    document.getElementById("sample6_address").value = addr;
                                    // 커서를 상세주소 필드로 이동한다.
                                    document.getElementById("sample6_detailAddress").focus();
                                }
                            }).open();
                        }
                    </script>

                <br>
                <input type="submit" value="등록">
            </form>
            </div>

        </body>
    </html>


{% endblock %}