mainapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('list/', views.notice_list, name='notice_list'),                   
    path('detail/<int:notice_id>', views.notice_detail, name='notice_detail'),                        
    path('register/', views.notice_register, name='notice_register'),                        
    path('update/<int:notice_id>', views.notice_update, name='notice_update'), 
    path('delete/<int:notice_id>', views.notice_delete, name='notice_delete'),
    path('weather/', views.weather, name='weather'),
    path('transport/', views.transport, name='transport'),             
 
]

sookmyungproject/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.views.home, name='home'),
    path('accounts/', include('accountsapp.urls')),
    path('library/', include('libraryapp.urls')),
    path('sookplace/', include('sookplaceapp.urls')),
    path('main/', include('mainapp.urls')),
    #path('transport/', include('transportapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models

# Create your models here.

class Notice(models.Model):
    title = models.CharField(max_length=255)
    link = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.title

mainapp/forms.py
from django import forms
from .models import Notice

class NoticeForm(forms.ModelForm):
    class Meta:
        model = Notice
        fields = ['title', ]

mainapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Notice
from .forms import NoticeForm
from .crawling import transportPrasing


# Create your views here.

##메인페이지
def home(request):
        return render(request, 'mainapp/home.html')

#공지 리스트
def notice_list(request):
    notices = Notice.objects               
    return render(request, 'mainapp/notice_list.html', {'notices' : notices})

#공지 상세페이지 (R)
def notice_detail(request, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    return render(request, 'mainapp/notice_detail.html',{'notice': notice})

#공지 등록 (C)
@login_required
def notice_register(request):
    if request.method == 'POST':
        form = NoticeForm(request.POST, request.FILES)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.save()
            return redirect('mainapp:notice_list')
    else : 
        form=NoticeForm()
        return render(request, 'mainapp/notice_register.html', {'form':form})


#공지 수정(U)
@login_required
def notice_update(request, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    if request.method=='POST':
        form = NoticeForm(request.POST, instance=notice)
        if form.is_valid():
            notice = form.save(commit=False)
            notice.save()
            return redirect('mainapp:notice_detail', notice_id=notice.pk)    
    else:
        form = NoticeForm(instance=notice)
        return render(request, 'mainapp/notice_update.html', {'form':form})


#공지 삭제(D)
@login_required
def notice_delete(request, notice_id):
    notice = get_object_or_404(Notice, pk=notice_id)
    notice.delete()
    return redirect('mainapp:notice_list')

def weather(request):
    return render(request, 'mainapp/weather.html')

def transport(request):
    ys04 = "101900002" ##용산04

    ys_smlibrary = "102000137"  ##숙명여대 도서관앞
    ys_smlibrary_ord="21"
    ys_smforntdoor = "102000140"  ##숙명여대정문
    ys_smforntdoor_ord = "22"
    ys_smbackgate = "102000141"  ##숙명여대 후문
    ys_smbackgate_ord = "23"

    bus400 = "100100596" ##400번 버스
    d_smfrontdoor = "102000139"  ##숙명여대 정문
    d_smfrontdoor_ord = "41"  
    d_smlibrary = "102000138"  ##숙명여대도서관앞
    d_smlibrary_ord = "42"
    u_smlibrary = "102000137"  ##숙명여대도서관앞
    u_smlibrary_ord = "63"
    u_smfrontdoor = "102000140"  ##숙명여대정문
    u_smfrontdoor_ord = "64"
    u_smbackgate = "102000141"  ##숙명여대후문
    u_smbackgate_ord = "65"
    
    ys04_smlibrary = transportPrasing(ys04, ys_smlibrary, ys_smlibrary_ord)
    ys04_smfrontdoor = transportPrasing(ys04, ys_smforntdoor, ys_smforntdoor_ord)
    ys04_smbackgate = transportPrasing(ys04, ys_smbackgate, ys_smbackgate_ord)

    bus400_d_smfrontdoor = transportPrasing(bus400, d_smfrontdoor, d_smfrontdoor_ord)
    bus400_d_smlibrary = transportPrasing(bus400, d_smlibrary, d_smlibrary_ord)
    bus400_u_smlibrary = transportPrasing(bus400, u_smlibrary, u_smlibrary_ord)
    bus400_u_smfrontdoor = transportPrasing(bus400, u_smfrontdoor, u_smfrontdoor_ord)
    bus400_u_smbackgate = transportPrasing(bus400, u_smbackgate, u_smbackgate_ord)

    return render(request, 'mainapp/transport.html', {'ys04_smlibrary':ys04_smlibrary, 'ys04_smfrontdoor':ys04_smfrontdoor, 'ys04_smbackgate':ys04_smbackgate, 
    'bus400_d_smfrontdoor':bus400_d_smfrontdoor, 'bus400_d_smlibrary':bus400_d_smlibrary, 
    'bus400_u_smlibrary':bus400_u_smlibrary, 'bus400_u_smfrontdoor':bus400_u_smfrontdoor, 'bus400_u_smbackgate':bus400_u_smbackgate}
)

mainapp/templates/mainapp/home.html
<!--http://127.0.0.1:8000/-->
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style type="text/css">
            .keyword{color:gray;font-weight:bold;}
            .keyword:hover{color:#04dbc9;}
            #introduce{line-height:20pt;}
            #ilike {margin-top:60px;line-height:20pt;}
            #goodat {margin-top:60px;line-height:20pt;}
            a{text-decoration:none;color:black; !important}
            #main_img{width:70%;height:500px;overflow:hidden;}
            </style>

           <script type="text/javascript">

            </script>
        </head>

        <body style="text-align:center;">

        <div id ="about"style="margin-top:12%"></div>
      <article>
         <p class="title" style="font-size:25pt;font-weight:bold;margin-top:50px;">ABOUT US</p>
         <p id="introduce"> 안녕하세요! <br>
            서버운영 20조 홈페이지에 오신 것을 환영합니다.<br>저희는 숙명여대생에게 가장 적합한 <b>교내정보</b>와
<b>교외정보</b>를<br> 한번에 볼 수 있는 '편리한 플렛폼'을 제공합니다.
</p>

      </article>
      <article>
            <p id="ilike"><em style="font-weight:bold; font-size:15pt;">"Development Environment"</em></br><br/>
                    <span class="keyword">Linux/Django/AWS</span><br><br>
                    <span class="keyword">HTML/CSS/Javascript/PHP</span><br><br>도서자료 검색 및 , 학교 주변 맛집 정보, 학교 주변 교통 정보 등을 알 수 있습니다.</p>


        <span><a style="box-shadow: 1px 1px 3px;border:1px solid;width:120px;height:30px;line-height:30px;display:inline-block;border-radius:5px;"  href="main/list/">학교 공지사항</a></span>
        </body>
    </html>


{% endblock %}

mainapp/templates/mainapp/notice_detail.html
<!--http://127.0.0.1:8000/main/detail/1-->
<!--맨 끝의 숫자는 게시물 번호!-->
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style type="text/css">
                a{text-decoration:none;color:black; !important}

            </style>
        </head>

        <body style="text-align:center;">
        <div style="width:100%;display:inline-block;">
            <h2 style="margin-top:12%">공지 사항</h2>

            <div style="display:inline-block;width:90%; height:2px; background-color:#171717; margin:40px 0 60px 0;"></div><br>
            <span style="font-size:20pt;">{{ notice.title }}</span><br> <!--notice게시물 제목-->
            <span style="display:inline-block;width:80%;text-align:right;margin:20px 0 15px 0;">{{ notice.date }}</span><br> <!--notice게시물 게시날짜-->
            <div style="display:inline-block;width:80%" id="content">{{ notice.describe }}</div><br> <!--notice게시물 내용-->

            <br>
            <!--수정하기 버튼-->
            <!--superuser만 수정버튼 보임-->
            <div style="float:right; margin-right:10%;">
            {% if user.is_superuser %}
                <a style=" margin-right:10px;box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;display:inline-block;border-radius:5px;" href="{% url 'mainapp:notice_update' notice.id %}">수정하기</a>
                <a style="box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;display:inline-block;border-radius:5px;" href="{% url 'mainapp:notice_delete' notice.id %}">삭제하기</a>
            {% endif %}
                </div>
        </div>

        </body>
    </html>


{% endblock %}

mainapp/templates/mainapp/notice_list.html
<!--http://127.0.0.1:8000/main/list/-->
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style type="text/css">
                a{text-decoration:none;color:black; !important}

            </style>
        </head>

        <body style="text-align:center;">
            <h2 style="margin-top:12%">공지 사항</h2>
            <div id="notice_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">
            <!--notice 게시판의 모든 글 불러오기&출력-->
            {% for notice in notices.all %}
            <br>
            <div id="notice_link" style="display:inline-block;width:95%;height:50px;border-bottom: 1px solid #848484;">
            <a href="{{notice.link}}" style="float:left;margin-left:20px;">{{ notice.title }}</a> <span style="float:right;margin-right:30px;color:848484">{{ notice.date }}</span>
            </div><br>
            {% endfor %}
            </div>
            <br>
            <!--superuser에게만 글쓰기 권한 주기-->
            {% if user.is_superuser %}
                <a style="float:right; margin-right:10%;box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;line-height:30px;display:inline-block;border-radius:5px; " href="{% url 'mainapp:notice_register' %}">글쓰기</a><br>
            {% endif %}
        </body>
    </html>


{% endblock %}

mainapp/templates/mainapp/notice_register.html
<!--http://127.0.0.1:8000/main/register/-->

    <!DOCTYPE html>
    <html>
        <head>

        </head>

        <body>
            {% extends 'base.html' %}

            {% block content %}
            <h1>notice_register.html</h1>
            <form method="POST">
                {% csrf_token %}
                제목 : {{ form.title }} <br>   <!--title 입력 폼-->

                <input type="submit" value="등록">
            </form>
        </body>
    </html>


{% endblock %}

mainapp/templates/mainapp/notice_update.html
<!--http://127.0.0.1:8000/main/update/1-->
<!--맨 끝의 숫자는 게시물 번호!-->

{% extends 'base.html' %}

{% block content %}

    <!DOCTYPE html>
    <html>
        <head>
            <style type="text/css">
                a{text-decoration:none;color:black; !important}
                #id_title{width:700px;}
                textarea{resize:none; width:700px;height:250px;}
            </style>
        </head>

        <body style="text-align:center;">
            <h2 style="margin-top:12%">공지 사항 수정</h2>
            <div id="notice_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">
                <form style="margin:50px 0 0 0" method="POST">
                    {% csrf_token %}
                    <span style="margin-right:10px;">제    목</span>{{ form.title }} <br> <br>  <!--title 입력 폼-->
                    <span style="display:inline-block;vertical-align:top;margin-right:10px;">내    용</span>{{ form.describe }}<br><br>  <!--describe 입력 폼-->
    
                    <input type="submit" value="등록">
                </form>
            </div>
        </body>
    </html>


{% endblock %}

mainapp/templates/mainapp/transport.html
<!DOCTYPE html>
<html>
    <head>
        <style>
            .contents{
                margin:50px;
                margin-top: 100px;
                text-align: center;
            }
            .up{
                width:90%;
                height:400px;
                margin:auto;
                margin-top: 80px;
                text-align:center;
            }
            .down{
                width:60%;
                height:400px;
                margin:auto;
                text-align:center;
            }
        </style>

    </head>
    {% extends 'base.html' %}

    {% block content %}
    <body>
        <div class="contents">
            <h2>버스 도착 정보</h2> 
            <div id="notice_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">

                <table class="up">
                    <tr>
                        <td>
                            <div>
                                <h4>숙명여대 도서관 앞</h4>
                                <img   width="250" src="https://postfiles.pstatic.net/MjAxOTEyMTlfMjE1/MDAxNTc2NzM1NjE2OTY5.PI8rAJYFX7xXRzN-oCsYT-2A1cYrNvuZqDHgEBJnQxog.V4Fvk3oGGGsA8o0Oui6rJbdzEW7T_1G7kr6lbvKUXO4g.JPEG.3jine33/KakaoTalk_20191219_150352795.jpg?type=w773"><br>
                                <br>
                                용산04 : {{ ys04_smlibrary }} <br>
                                400번 : {{ bus400_u_smlibrary }}<br>
                            </div>
                        </td>    
                            
                            


                        <td>
                            <div>
                                <h4>숙명여대 정문</h4>
                                <img   width="250" src="https://postfiles.pstatic.net/MjAxOTEyMTlfMjA4/MDAxNTc2NzM1NjE2OTg3.FizGBCGMYGz72q6CuXoqaLbkLrzksbSMtX9vXEeoHw8g.zn2pc78wvsjtN-U280SvqUMPptaDnsLR_kRHYGrJ5HYg.JPEG.3jine33/KakaoTalk_20191219_150352795_03.jpg?type=w773"><br>
                                <br>
                                용산04 : {{ ys04_smfrontdoor }}<br>
                                400번 : {{ bus400_u_smfrontdoor }}<br>
                            </div>
                        </td>

                            

                        <td>
                            <div>
                                <h4>숙명여대 후문</h4>
                                <img   width="250" src="https://postfiles.pstatic.net/MjAxOTEyMTlfOTIg/MDAxNTc2NzM1NjE3MDA0.p7ha5CQslHfrLqNCMxd9ZPJWdlq02ziw7hbCuIVXlM0g.bpJ63-uczv4ysS6HPzznsd5fZ9Kkdzxd26yI_vUMzSYg.JPEG.3jine33/KakaoTalk_20191219_150352795_02.jpg?type=w773"><br>
                                <br>
                                용산04 : {{ ys04_smbackgate }}<br>
                                400번 : {{ bus400_u_smbackgate }}<br>
                            </div>
                        </td>
                    </tr>
                </table>
                
                
                <table class="down">
                    <tr>
                        <td>
                            <div>
                                <h4>숙명여대 정문</h4>
                                <img   width="250" src="https://postfiles.pstatic.net/MjAxOTEyMTlfNTYg/MDAxNTc2NzM1NjE2OTgz.Gd7ZjjSRESa8eKwH_c67UBoP2aH2SMSh_5lZwzc5BFQg.dTi1q3XAznwQMp7nL2Epe_yS_-Nlpy_s3H0Hmw8AXmAg.JPEG.3jine33/KakaoTalk_20191219_150352795_01.jpg?type=w773"><br>
                                <br>
                                400번 : {{  bus400_d_smfrontdoor }}<br>
                            </div>
                        </td>

                        <td>
                            
                            
                            <div>
                                <h4>숙명여대 도서관 앞</h4>
                                <img   width="250" src="https://postfiles.pstatic.net/MjAxOTEyMTlfMTUy/MDAxNTc2NzM1NjE3MDE0.0qs9uP-j6eHCHIxklqN89bz-7nWFF-X-NLy_Cn-R-4kg.CH_Hen4hswb8qtPV0DNO_18QTRLJ4Kg-i_kuRfdKl4sg.JPEG.3jine33/KakaoTalk_20191219_150352795_04.jpg?type=w773"><br>
                                <br>
                                400번 : {{ bus400_d_smlibrary }}<br>
                            </div>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        {% endblock %} 
    </body>
</html>

mainapp/templates/mainapp/weather.html
<!DOCTYPE html>
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous" ></script>
    <style>
        .container{
            text-align: center;
            margin-top:60px;
            vertical-align: middle;
            white-space: nowrap;
            position: relative;
        }
    </style>
</head>

<body style="text-align: center;">
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <p style="font-weight:bold; font-size: 20px">날씨검색 <input id="city" placeholder="도시명을 입력하세요" style="text-align: center;"></input>
        <button id="getWeatherForcast" style="font-weight:bold; font-family:sans-serif">GET WEATHER</button></p>
<div class="ShowWeatherForcast"></div>
</div>
<script type="text/javascript">
   $(document).ready(function(){
      $("#getWeatherForcast").click(function(){
      var city = $("#city").val();
      var key  = '3ba2d171606d0102d383b2a52fd76475';
      $.ajax({
              url:'http://api.openweathermap.org/data/2.5/weather',
              dataType:'json',
              type:'GET',
              data:{q:city, appid: key, units: 'metric'},

              success: function(data){
                var wf = '';
                $.each(data.weather, function(index, val){

                  wf += '<p><b>' + data.name + "</b></p>"+
                  data.main.temp + '&deg;C ' +
                  ' | ' + val.main + ", " + val.description

                });

               $(".ShowWeatherForcast").html(wf);
              },
                error:function(){
              }
            });

      });
    });
  </script>


{% endblock %}
</body>
</html>