libraryapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='libraryapp'

urlpatterns = [
    path('list/', views.book_list, name='book_list'),                   
    path('detail/<int:book_id>', views.book_detail, name='book_detail'),                        
    path('register/', views.book_register, name='book_register'),                        
    path('update/<int:book_id>', views.book_update, name='book_update'), 
    path('delete/<int:book_id>', views.book_delete, name='book_delete'),             
    path('result/', views.book_result, name="book_result"),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('list/', views.notice_list, name='notice_list'),                   
    path('detail/<int:notice_id>', views.notice_detail, name='notice_detail'),                        
    path('register/', views.notice_register, name='notice_register'),                        
    path('update/<int:notice_id>', views.notice_update, name='notice_update'), 
    path('delete/<int:notice_id>', views.notice_delete, name='notice_delete'),
    path('weather/', views.weather, name='weather'),
    path('transport/', views.transport, name='transport'),             
 
]

sookmyungproject/urls.py
from django.contrib import admin
from django.urls import path, include
import mainapp.views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp.views.home, name='home'),
    path('accounts/', include('accountsapp.urls')),
    path('library/', include('libraryapp.urls')),
    path('sookplace/', include('sookplaceapp.urls')),
    path('main/', include('mainapp.urls')),
    #path('transport/', include('transportapp.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

libraryapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Book(models.Model):
    CATEGORY = (
        ('fiction', '소설'),
        ('society/culture', '사회/문화'),
        ('IT', 'IT'),
    )

    title= models.CharField(max_length=255)  ##책 제목 
    author= models.CharField(max_length=255)  ## 책 저자
    category=models.CharField(max_length=255, choices=CATEGORY)  ##책 카테고리
    publisher= models.CharField(max_length=255)  ## 책 출판사
    pub_year= models.IntegerField()  ##책 출판년도
    location= models.CharField(max_length=255)  ##책 소장위치
    describe = models.TextField()  ##책 소개
    photo = models.ImageField(null=True,blank=True, upload_to='library/') ##책 사진

    def __str__(self):
        return self.title    


class Scrap(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)    

libraryapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'author', 'category', 'publisher', 'pub_year', 
                'location', 'describe', 'photo']

libraryapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Book
from .forms import BookForm


# Create your views here.

#책 리스트
def book_list(request):
    books = Book.objects               
    return render(request, 'libraryapp/book_list.html', {'books' : books})

#책 상세페이지 (R)
def book_detail(request, book_id):    
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'libraryapp/book_detail.html',{'book': book})


#책 등록 (C)
@login_required
def book_register(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            return redirect('libraryapp:book_list')
    else : 
        form=BookForm()
        return render(request, 'libraryapp/book_register.html', {'form':form})


#책 수정(U)
@login_required
def book_update(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method=='POST':
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            book = form.save(commit=False)
            book.save()
            return redirect('libraryapp:book_detail', book_id=book.pk)    
    else:
        form = BookForm(instance=book)
        return render(request, 'libraryapp/book_update.html', {'form':form})

#책 삭제(D)
@login_required
def book_delete(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    book.delete()
    return redirect('libraryapp:book_list')

#책 필터링
def book_result(request):
    book_object = Book.objects
    query = request.GET.get('query','')
    
    if query:
        book_object = book_object.filter(title__contains=query)
        return render(request,'libraryapp/book_result.html',{'result':book_object} )
    else :
        return redirect('libraryapp:book_list')

libraryapp/templates/libraryapp/book_detail.html
<!--http://127.0.0.1:8000/library/detail/1-->
<!--마지막 숫자는 글번호-->
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style type="text/css">
                a{text-decoration:none;color:black; !important}

            </style>
        </head>

        <body style="text-align:center;">
        <div style="width:100%;display:inline-block;">
            <h2 style="margin-top:12%">이달의 도서</h2>
                <div style="display:inline-block;width:90%; height:2px; background-color:#171717; margin:40px 0 60px 0;"></div><br>
                <span style="font-size: 20pt;">{{ book.title }}</span><br><br> <!--책 제목-->

                <div style="display:inline-block;width:80%" id="lib_content">
                    {{ book.author }}<!--책 저자-->
                    {{ book.publisher }}<br> <!--책 출판사-->
                    {{ book.category }} <!--책 카테고리-->
                    {{ book.pub_year }} <!--책 출판년도-->
                    {{ book.location }}<br> <!--책 소장위치-->
                    {{ book.describe }}<br> <!--책 소개--><br>
                    <img src="{{ book.photo.url }}" width=200><br> <!--책 사진-->
                </div><br>

            <br>
            <!--수정하기 버튼-->
            <!--superuser만 수정버튼 보임-->
            <div style="float:right; margin-right:10%;">
                {% if user.is_superuser %}
                <a style="margin-right:10px;box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;display:inline-block;border-radius:5px;" href="{% url 'libraryapp:book_update' book.id %}">수정하기</a>
                <a style="box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;display:inline-block;border-radius:5px;" href="{% url 'libraryapp:book_delete' book.id %}">삭제하기</a>
                {% endif %}
            </div>
        </div>
        </body>
    </html>


{% endblock %}

libraryapp/templates/libraryapp/book_list.html
<!--http://127.0.0.1:8000/library/list/-->
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style>
                .container{
                    text-align: right;
                    margin-top:10px;
                    vertical-align: middle;
                    white-space: nowrap;
                    position: relative;
                }
                a{text-decoration:none;color:black; !important}
            </style>
        </head>

        <body style="text-align: center;">
            <h2 style="margin-top:12%">이달의 도서</h2>

            <!--필터링(검색)-->
            <div class = "container">
                <form action="{% url 'libraryapp:book_result' %}" method="get">
                <input type="search" placeholder="책제목을 입력하세요" name="query" style="text-align: center;">
                <input type="submit" name="" value="검색">
                </form>
            </div>

            <div id="lib_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">
            <!--글 목록-->
            {% for book in books.all %}
            <br>
            <div id="lib_link" style="display:inline-block;width:95%;height:50px;border-bottom: 1px solid #848484;">
                <a href="{% url 'libraryapp:book_detail' book.id %}" style="margin-left:-65%;font-weight: bold; font-size: 14pt; color: #1D375F;">{{ book.title }}</a>
                <span style="float:right;margin-right:30px;color:848484">{{ book.author }} {{ book.publisher }}</span>
            </div>
            <br>
            {% endfor %}
            </div><br>

            <!--superuser에게만 글쓰기 권한 주기-->
            {% if user.is_superuser %}
                <a style="float:right; margin-right:10%;box-shadow: 1px 1px 3px;border:1px solid;width:80px;height:30px;line-height:30px;display:inline-block;border-radius:5px; " href="{% url 'libraryapp:book_register' %}">글쓰기</a><br>
            {% endif %}

        </body>
    </html>


{% endblock %}

libraryapp/templates/libraryapp/book_register.html
<!--http://127.0.0.1:8000/library/register/-->
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style type="text/css">
            #id_title{width:700px;}
            textarea{resize:none; width:700px;height:250px;}
                a{text-decoration:none;color:white; !important}

            </style>
        </head>

        <body style="text-align:center;">
            <h2 style="margin-top:12%">이달의 도서 등록</h2>
            <div id="lib_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">
            <form style="margin:50px 0 10px 0;" method="POST" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <span style="margin-right:10px;">제   목</span> {{ form.title }} <br><br>   <!--title 입력 폼-->
                <span style="margin-right:10px;">저   자</span> {{ form.author }}
                <span style="margin-right:10px;">카테고리</span> {{ form.category }}
                <span style="margin-right:10px;">출 판 사</span> {{ form.publisher }} <br><br>
                <span style="margin-left:6%;margin-right:10px;">출판년도</span> {{ form.pub_year }}
                <span style="margin-right:10px;">소장위치</span> {{ form.location }}
                <span style="margin-right:10px;">사   진</span> {{ form.photo }} <br><br>
                <span style="display:inline-block;vertical-align:top;margin-right:10px;margin-left:-1%;">책 소 개</span> {{ form.describe }}<br>  <!--describe 입력 폼-->
                <br>
                <input type="submit" value="등록">
            </form>
            </div>
        </body>
    </html>


{% endblock %}

libraryapp/templates/libraryapp/book_result.html
<!--http://127.0.0.1:8000/library/result/?query=test-->
<!--query= 뒤에 있는 단어가 검색 단어 (위의 경우는 test를 검색한것)-->

{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style>
                .container{
                    text-align: right;
                    margin-top:10px;
                    vertical-align: middle;
                    white-space: nowrap;
                    position: relative;
                }
                a{text-decoration:none;color:black; !important}
            </style>
        </head>

        <body style="text-align: center;">
            <h2 style="margin-top:12%">검색결과</h2>

            <!--필터링(검색)-->
            <div class = "container">
                <form action="{% url 'libraryapp:book_result' %}" method="get">
                <input type="search" placeholder="책제목을 입력하세요" name="query" style="text-align: center;">
                <input type="submit" name="" value="검색">
                </form>
            </div>

            <div id="lib_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">
            <!--검색 결과-->
            {% for result in result.all %}
            <br>
            <div id="lib_link" style="display:inline-block;width:95%;height:50px;border-bottom: 1px solid #848484;">
                <a href="{% url 'libraryapp:book_detail' result.id %}" style="margin-left:-65%;font-weight: bold; font-size: 14pt; color: #1D375F;">{{ result.title }}</a>
                <span style="float:right;margin-right:30px;color:848484">{{ result.author }} {{ result.publisher }}</span>
            </div><br>
                {% endfor %}
            </div><br>



        </body>
    </html>


{% endblock %}

libraryapp/templates/libraryapp/book_update.html
<!--http://127.0.0.1:8000/library/update/1-->
<!--마지막 숫자는 글번호-->
{% extends 'base.html' %}

{% block content %}
    <!DOCTYPE html>
    <html>
        <head>
            <style>
            <style type="text/css">
                a{text-decoration:none;color:black; !important}
                #id_title{width:700px;}
                textarea{resize:none; width:700px;height:250px;}
            </style>
        </head>

        <body style="text-align:center;">
            <h2 style="margin-top:12%">이달의 도서 수정</h2>
            <div id="lib_board" style="display:inline-block;width:90%;border-top:2px solid #171717; margin:30px 0 30px 0">
                <form  style="margin:50px 0 0 0" method="POST" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                <span style="margin-right:10px;">제   목</span> {{ form.title }} <br><br>   <!--title 입력 폼-->
                <span style="margin-right:10px;">저   자</span> {{ form.author }}
                <span style="margin-right:10px;">카테고리</span> {{ form.category }}
                <span style="margin-right:10px;">출 판 사</span> {{ form.publisher }} <br><br>
                <span style="margin-left:6%;margin-right:10px;">출판년도</span> {{ form.pub_year }}
                <span style="margin-right:10px;">소장위치</span> {{ form.location }}<br><br>
                <span style="margin-right:10px;">사   진</span> {{ form.photo }} <br><br>
                <span style="display:inline-block;vertical-align:top;margin-right:10px;margin-left:-1%;">책 소 개</span> {{ form.describe }}<br><br>
                <input type="submit" value="등록">
                </form>
            </div>

    
        </body>
    </html>


{% endblock %}